name: pipeline de testes

on:
  push:
    brances:
      - main
    pull_requestes:
      - main
jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
       - name: Checar o repositório
         uses: actions/checkout@v2

       - name: Executar testes
         run: |
            python -m unittest discover